version: '3.7'
services:
    api:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
      - ./src:/usr/src/app/src
      container_name: server-blog
      ports:
        - '4000:4000'